In [0]:
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
ratings=pd.read_csv("/content/drive/My Drive/Dataset/ratings.csv")
ratings.fillna(0, inplace=True)
data=ratings.sort_values(by=["book_id"])
data=data[0:5000]
k=set(data.user_id)
b=set(data.book_id)
user=list(k)
book=list(b)

In [0]:
for i in user:
  for j in book:
    for ind in data.index:
      if ((i==data["user_id"][ind]) & (j==data["book_id"][ind])):
        print("add")
        v=data["rating"][ind]
        df[j][i]=v
        print(j,i)
        break

In [0]:
df.fillna(0,inplace=True)
df

       1  2  3  4  5  6  7  8  9  10  ...  41  42  43  44  45  46  47  48  49  50
26629  4  4  4  4  5  0  4  0  0   0  ...   0   4   4   0   0   0   0   0   4   0
10246  4  0  1  0  4  0  4  5  0   0  ...   0   0   0   0   0   0   0   0   0   0
22534  0  0  0  0  0  3  0  0  0   0  ...   0   0   0   0   0   0   3   0   0   0
24582  0  0  0  0  0  0  0  0  0   0  ...   4   0   0   0   0   0   0   0   2   0
10249  0  0  5  0  0  0  5  0  0   4  ...   5   0   3   4   0   3   3   3   5   0
...   .. .. .. .. .. .. .. .. ..  ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
20467  3  0  0  4  4  0  0  0  0   0  ...   0   0   0   0   0   0   0   0   0   0
49138  0  0  0  0  0  5  0  0  0   0  ...   0   0   0   0   0   0   0   0   0   0
24567  0  0  0  0  0  0  0  0  0   0  ...   0   0   0   0   0   0   0   0   4   0
16377  4  0  1  0  0  0  0  0  0   0  ...   0   0   0   1   5   5   0   5   1   0
53245  4  0  0  5  0  0  0  0  0   0  ...   0   0   0   0   0   0   4   0   0   0

[445 rows x 50 columns]

In [0]:
df.to_csv("clean.csv")
from google.colab import files
files.download('clean.csv')